
apiVersion: v1
kind: Namespace
metadata:
  name: client-api
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-api
    app.kubernetes.io/name: client-api
  name: client-api
  namespace: client-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: client-api
  strategy: {}
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
      - image: vimuchiaroni/client-api:1.2
        name: client-api
        ports:
          - name: http
            containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: CART_SERVICE_URL
            value: 'http://cart-api.cart-api.svc.cluster.local:8000'
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: 
                  - client-api
              topologyKey: "kubernetes.io/hostname"

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: client-api
    app.kubernetes.io/name: client-api
  name: client-api
  namespace: client-api
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: client-api
  type: ClusterIP

---
apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: client-api.client-api.svc.cluster.local
  namespace: client-api
spec:
  routes:
  - condition:
      method: GET
      pathRegex: /retries/upstream/cart/\d+
    name: GET
    isRetryable: false
  - condition:
      method: POST
      pathRegex: /
    name: POST
    isRetryable: false