
apiVersion: v1
kind: Namespace
metadata:
  name: cart-api
  annotations:
    linkerd.io/inject: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cart-api
    app.kubernetes.io/name: cart-api
  name: cart-api
  namespace: cart-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cart-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cart-api
    spec:
      containers:
      - image: vimuchiaroni/cart-api:1.1
        name: cart-api
        ports:
          - name: http
            containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /healthcheck
            port: 8000
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values: 
                  - cart-api
              topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: cart-api
    app.kubernetes.io/name: cart-api
  name: cart-api
  namespace: cart-api
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: cart-api
  type: ClusterIP

---

apiVersion: linkerd.io/v1alpha2
kind: ServiceProfile
metadata:
  creationTimestamp: null
  name: cart-api.cart-api.svc.cluster.local
  namespace: cart-api
spec:
  retryBudget:
    retryRatio: 0.15
    minRetriesPerSecond: 10
    ttl: 10s
  routes:
  - condition:
      method: GET
      pathRegex: /api/cart
    name: GET /api/cart
    isRetryable: true
  - condition:
      method: GET
      pathRegex: /api/retries/\d+
    name: GET /api/retries
    isRetryable: true
  - condition:
      method: POST
      pathRegex: /api/create/cart
    name: POST /api/create/cart
    isRetryable: true